type = "webpack"
account_id = "661484bfa811d50ad0a7c946485ad9ae"
zone_id = "d53c5683f00e72915fb714532816144a"

[env.staging]
name = "tiffany-moeller-staging"
workers_dev = false
route = "staging.tiffanymoeller.com/*"

[env.production]
name = "tiffany-moeller"
workers_dev = false
route = "tiffanymoeller.com/*"

[site]
bucket = "./public"
entry-point = "workers-site"